# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG=cpio
GOFILES=\
	common.go\
	reader.go\
	writer.go\

include $(GOROOT)/src/Make.pkg
